### ISSUE TITLE
TODO for key value MVP

### ISSUE THREAD

**Issue by jpilapil** [jpilapil/key-value-pair#1]
- [x]  build basic landing page
- [ ]  username, password, interested tech, gender, pref gender
- [ ]  get tech api to work
- [x]  matches page
- [x] member since and interested tech on other users
- [ ]  contact other users (email for now)
- [ ] add sort dropdown that is populated with users interested tech

extra:
- [ ] cloud9
- [ ] track if users are online
- [ ] implement in app messaging
